### ISSUE TITLE
Cache-handler plugin is throwing an unhandled error

### ISSUE THREAD

**Issue by philbooth** [philschatz/octokat.js#135]
I tried to update from 0.4 to 0.6 today but my site falls over with this unhandled error:

```
/mnt/app/node_modules/octokat/dist/node/plugins/cache-handler.js:82
            throw new Error('ERROR: Bug in Octokat cacheHandler. It had an eTag but not the cached response');
            ^

Error: ERROR: Bug in Octokat cacheHandler. It had an eTag but not the cached response
    at CacheHandler.responseMiddlewareAsync (/mnt/app/node_modules/octokat/dist/node/plugins/cache-handler.js:82:19)
    at dispatchEvent (/mnt/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/mnt/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/mnt/app/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Is there something I'm supposed to do to prevent this, or should I be using the `uncaughtException` event or something?

I'm happy to dig in some more if you need me to debug it. Just let me know what I should be looking at if that's the case.

**Comment by callum-p** [comment]
:+1: just got hit by this now and there is no way to disable caching that I can see.

I can see the main constructor accepts the option `useETags: false` but it doesn't seem to do anything.
