### ISSUE TITLE
using a 'token' in results in an error

### ISSUE THREAD

**Issue by orizens** [philschatz/octokat.js#51]
hi @philschatz .

I'm using the web flow for retreiving a token - so eventually my app receives a **code** parameter in the query string after github redirects to my app.  
when i use this **code** like so:  
```
data.github = new Octokat({
	token: token
});
```
I'm trying to fetch one of my repos and i'm getting this error in the browser console:   
```
Uncaught (in promise) Error: {
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}

  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}

    at http://localhost:3000/octokat.js:1001:17
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:3000/octokat.js:835:16)
```  
Anything i'm missing here?

**Comment by orizens** [comment]
I figured it out.  
I accediently misplaced the 'code' as the 'token' and was missing the step of retreiving a real 'access_token' with the 'code' as descripted in the github's oauth 2 flow.
