### ISSUE TITLE
Getting reference error on fetch if there is no response

### ISSUE THREAD

**Issue by RichardLitt** [philschatz/octokat.js#87]
I don't think this is a problem with ocotkat, but rather a problem with my implementation. But I'm not sure how else to diagnose this problem. 

Here is my code, roughly:

```js
return Promise.try(function () {
    return octo.notifications.fetch()
  }).each(function (repo) {
    // Do a lot of stuff
  }).catch(function (err) {
    console.log(err)
  })
```

If there are no notifications to fetch, I get this error:

```sh
/Users/richard/src/ignore-github-users/node_modules/octokat/dist/node/request.js:196
              return cb(null, jqXHR.responseText, status, jqXHR);
                                                  ^

ReferenceError: status is not defined
    at /Users/richard/src/ignore-github-users/node_modules/octokat/dist/node/request.js:196:51
    at xhr.onreadystatechange (/Users/richard/src/ignore-github-users/node_modules/octokat/dist/node/request.js:43:18)
    at dispatchEvent (/Users/richard/src/ignore-github-users/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/richard/src/ignore-github-users/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/richard/src/ignore-github-users/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:450:9)
    at process._tickCallback (node.js:364:17)
```

Do you have any ideas what I might be doing wrong, here? Shouldn't the `try` catch the error, and log it? It doesn't. I am very confused. 

Thank you so much.

**Comment by philschatz** [comment]
Oops, that's a bug in octokat! (fixed in #88) I'm guessing some versions of node silently ignored the error (which is why I had not caught it in the tests). Which version of node are you using (or any special flags) so I can add them to the Travis tests?

**Comment by RichardLitt** [comment]
```sh
🐕  node -v
v5.0.0
```

No special flags. Details: https://github.com/RichardLitt/ignore-github-users

**Comment by RichardLitt** [comment]
Works. Thanks!
